from __future__ import annotations

"""Host-owned Tier 1 review catalog for the Phase 12 cached AI rollout.

These packets are deliberately non-player and non-authoritative.  They provide
semantic skeletons plus deterministic fallback wording for review/batch tooling;
no packet can settle money, success/failure, cooldowns or inventory.
"""

from app.ai_director import AIDirectorPacket


TIER1_REVIEW_PACKETS: tuple[AIDirectorPacket, ...] = (
    AIDirectorPacket(
        content_key="work_shift_opening_warehouse",
        family="work",
        semantic_slot="shift_opening",
        fallback_title="Indul a műszak",
        fallback_description="A raktárban lassan felpörög a műszak, mindenki elfoglalja a helyét.",
        facts={"location": "raktár", "moment": "műszakkezdés"},
        required_terms=("raktár",),
        tags=("tier1", "work", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="work_shift_routine_cnc",
        family="work",
        semantic_slot="routine_change",
        fallback_title="Megváltozott a ritmus",
        fallback_description="A CNC környékén átrendeződik a napi munkaritmus, de a feladat menete változatlan marad.",
        facts={"location": "CNC", "scope": "munkaritmus"},
        required_terms=("cnc",),
        tags=("tier1", "work", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="work_break_room_note",
        family="work",
        semantic_slot="ambient_note",
        fallback_title="Szünet előtti moraj",
        fallback_description="A pihenő közelében mindenki a következő munkaszakaszra készül.",
        facts={"location": "pihenő", "moment": "munkaszakasz"},
        required_terms=("pihenő",),
        tags=("tier1", "work", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="crime_street_rumor",
        family="crime",
        semantic_slot="street_rumor",
        fallback_title="Furcsa szóbeszéd járja",
        fallback_description="Az utcán egy bizonytalan pletyka terjed, de semmi sem utal biztos lehetőségre.",
        facts={"source": "utca", "certainty": "bizonytalan"},
        required_terms=("utca",),
        tags=("tier1", "crime", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="crime_quiet_corner",
        family="crime",
        semantic_slot="ambient_pressure",
        fallback_title="Túl nagy a csend",
        fallback_description="A környék szokatlanul csendes, ezért minden mozdulat feltűnőbbnek tűnik.",
        facts={"context": "környék", "mood": "csendes"},
        required_terms=("környék",),
        tags=("tier1", "crime", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="crime_contact_delay",
        family="crime",
        semantic_slot="contact_delay",
        fallback_title="Késik a jelzés",
        fallback_description="A kapcsolat felől egyelőre nem érkezik új jelzés, a helyzet nyitott marad.",
        facts={"source": "kapcsolat", "state": "nincs új jelzés"},
        required_terms=("kapcsolat",),
        tags=("tier1", "crime", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="search_bus_stop",
        family="search",
        semantic_slot="small_discovery",
        fallback_title="Valami feltűnik a megállónál",
        fallback_description="A buszmegálló környékén akad egy apró részlet, ami egy pillanatra magára vonja a figyelmet.",
        facts={"location": "buszmegálló", "scope": "apró részlet"},
        required_terms=("buszmegálló",),
        tags=("tier1", "search", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="search_market_edge",
        family="search",
        semantic_slot="small_discovery",
        fallback_title="A piac szélén",
        fallback_description="A piac szélén a megszokottnál több apróság kerül szem elé.",
        facts={"location": "piac", "scope": "apró részlet"},
        required_terms=("piac",),
        tags=("tier1", "search", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="search_station_walk",
        family="search",
        semantic_slot="ambient_search",
        fallback_title="Egy kör az állomásnál",
        fallback_description="Az állomás környékén végigsétálva néhány szokatlan részlet kerül előtérbe.",
        facts={"location": "állomás", "scope": "környék"},
        required_terms=("állomás",),
        tags=("tier1", "search", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="beg_square_crowd",
        family="beg",
        semantic_slot="crowd_mood",
        fallback_title="Mozgalmasabb lett a tér",
        fallback_description="A téren változik a járókelők ritmusa, de senki reakciója nincs előre eldöntve.",
        facts={"location": "tér", "subject": "járókelők"},
        required_terms=("tér",),
        tags=("tier1", "beg", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="beg_station_flow",
        family="beg",
        semantic_slot="crowd_mood",
        fallback_title="Hullámokban érkeznek az emberek",
        fallback_description="Az állomás előtt hol sűrűbb, hol ritkább a gyalogosforgalom.",
        facts={"location": "állomás", "subject": "gyalogosforgalom"},
        required_terms=("állomás",),
        tags=("tier1", "beg", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="beg_market_exit",
        family="beg",
        semantic_slot="crowd_mood",
        fallback_title="Záráshoz közeledik a piac",
        fallback_description="A piac kijáratánál lassan átrendeződik a tömeg, ahogy közeledik a nap vége.",
        facts={"location": "piac", "moment": "nap vége"},
        required_terms=("piac",),
        tags=("tier1", "beg", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="career_generic_team_handoff",
        family="career",
        semantic_slot="team_handoff",
        fallback_title="Műszakváltás",
        fallback_description="A csapat átadja a következő feladatokhoz szükséges információkat.",
        facts={"subject": "csapat", "moment": "műszakváltás"},
        required_terms=("csapat",),
        tags=("tier1", "career", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="career_generic_busy_period",
        family="career",
        semantic_slot="workload_change",
        fallback_title="Sűrűbb lett a nap",
        fallback_description="A munkahelyen több feladat kerül egyszerre előtérbe, ezért fontosabbá válik a sorrend.",
        facts={"context": "munkahely", "change": "több feladat"},
        required_terms=("munkahely",),
        tags=("tier1", "career", "cached_review"),
    ),
    AIDirectorPacket(
        content_key="career_generic_end_of_shift",
        family="career",
        semantic_slot="shift_closing",
        fallback_title="Közeledik a műszak vége",
        fallback_description="A csapat a műszak utolsó feladatait rendezi és készül az átadásra.",
        facts={"subject": "csapat", "moment": "műszak vége"},
        required_terms=("csapat",),
        tags=("tier1", "career", "cached_review"),
    ),
)
