# W22.8 isolated proof support: exact current defaults referenced by app.config.
# This is not a release-source claim; the full release economy_config is covered by local 320/320 regression.
STARTING_BALANCE = 25_000
AUTO_EVENT_MIN_SECONDS = 15 * 60
AUTO_EVENT_MAX_SECONDS = 90 * 60
EVENT_MIN_REWARD = 1_000
EVENT_JOIN_MIN_SECONDS = 15
EVENT_JOIN_MAX_SECONDS = 600
BOMB_MIN_ENTRY = 5_000
BOMB_ROUND_MIN_SECONDS = 5
BOMB_ROUND_MAX_SECONDS = 120
AUTO_EVENT_JOIN_SECONDS = 30
AUTO_SAFE_MIN_REWARD = 100_000
AUTO_SAFE_MAX_REWARD = 500_000
AUTO_BOMB_MIN_ENTRY = 25_000
AUTO_BOMB_MAX_ENTRY = 150_000
AUTO_BOMB_ROUND_SECONDS = 15
AUTO_EVENT_ACTIVITY_MESSAGES = 20
AUTO_EVENT_ACTIVITY_WINDOW_MINUTES = 30
AUTO_EVENT_ACTIVITY_MIN_USERS = 4
AUTO_EVENT_ACTIVITY_USER_COOLDOWN_SECONDS = 5
