from __future__ import annotations
from app.database_support import *

class DatabaseMixin1:
        def __init__(self, path: str, starting_balance: int) -> None:
            self.path = path
            self.starting_balance = starting_balance
            self.guild_state_repository = GuildStateRepository(path)

        async def _ensure_user_column(self, db: aiosqlite.Connection, name: str, definition: str) -> None:
            cursor = await db.execute('PRAGMA table_info(users)')
            columns = {str(row[1]) for row in await cursor.fetchall()}
            if name not in columns:
                await db.execute(f'ALTER TABLE users ADD COLUMN {name} {definition}')

        async def _ensure_character_foundation_schema(self, db: aiosqlite.Connection) -> None:
            """Install the additive RP Character Foundation schema on both backends.

            This is intentionally non-destructive and independent from the old DB-1
            migration. Existing wallet/business/crew/etc. rows are never copied or
            rewritten here.
            """
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS characters (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    character_name TEXT NOT NULL,\n                    age INTEGER NOT NULL,\n                    birthplace TEXT NOT NULL,\n                    background_key TEXT NOT NULL,\n                    home_city_key TEXT NOT NULL,\n                    current_city_key TEXT NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    schema_version INTEGER NOT NULL DEFAULT 1,\n                    created_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    finalized_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id)\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS characters (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    character_name VARCHAR(64) NOT NULL,\n                    age SMALLINT UNSIGNED NOT NULL,\n                    birthplace VARCHAR(128) NOT NULL,\n                    background_key VARCHAR(32) NOT NULL,\n                    home_city_key VARCHAR(32) NOT NULL,\n                    current_city_key VARCHAR(32) NOT NULL,\n                    status VARCHAR(24) NOT NULL DEFAULT 'active',\n                    schema_version INT UNSIGNED NOT NULL DEFAULT 1,\n                    created_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    finalized_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    KEY idx_characters_city (guild_id, current_city_key, status),\n                    KEY idx_characters_home_city (guild_id, home_city_key, status)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS character_creation_drafts (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    character_name TEXT,\n                    age INTEGER,\n                    birthplace TEXT,\n                    background_key TEXT,\n                    start_city_key TEXT,\n                    step_key TEXT NOT NULL DEFAULT 'basics',\n                    created_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    expires_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id)\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS character_creation_drafts (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    character_name VARCHAR(64) NULL,\n                    age SMALLINT UNSIGNED NULL,\n                    birthplace VARCHAR(128) NULL,\n                    background_key VARCHAR(32) NULL,\n                    start_city_key VARCHAR(32) NULL,\n                    step_key VARCHAR(32) NOT NULL DEFAULT 'basics',\n                    created_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    expires_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    KEY idx_character_drafts_expiry (expires_at)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS character_history (\n                    event_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    event_key TEXT NOT NULL,\n                    title TEXT NOT NULL,\n                    description TEXT NOT NULL,\n                    metadata_json TEXT NOT NULL,\n                    created_at TEXT NOT NULL,\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS character_history (\n                    event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    event_key VARCHAR(64) NOT NULL,\n                    title VARCHAR(128) NOT NULL,\n                    description LONGTEXT NOT NULL,\n                    metadata_json LONGTEXT NOT NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (event_id),\n                    KEY idx_character_history_user (guild_id, user_id, created_at),\n                    KEY idx_character_history_event (guild_id, user_id, event_key),\n                    CONSTRAINT fk_character_history_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_characters_city ON characters(guild_id,current_city_key,status)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_characters_home_city ON characters(guild_id,home_city_key,status)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_drafts_expiry ON character_creation_drafts(expires_at)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_history_user ON character_history(guild_id,user_id,created_at)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_history_event ON character_history(guild_id,user_id,event_key)')

        async def _ensure_career_v2_schema(self, db: aiosqlite.Connection) -> None:
            """Install the additive Career V2 employment schema on both backends.

            Employment is deliberately separate from legacy ``job_mastery`` and
            ``job_history``: one answers *where you work now*, the others preserve
            long-term experience and completed shifts.
            """
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS career_employment (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    career_key TEXT NOT NULL,\n                    city_key TEXT NOT NULL,\n                    hired_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS career_employment (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    career_key VARCHAR(48) NOT NULL,\n                    city_key VARCHAR(32) NOT NULL,\n                    hired_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    KEY idx_career_employment_city (guild_id, city_key, career_key),\n                    CONSTRAINT fk_career_employment_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS career_history (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    career_key TEXT NOT NULL,\n                    city_key TEXT NOT NULL,\n                    hired_at TEXT NOT NULL,\n                    ended_at TEXT NOT NULL,\n                    reason TEXT NOT NULL DEFAULT 'quit'\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS career_history (\n                    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    career_key VARCHAR(48) NOT NULL,\n                    city_key VARCHAR(32) NOT NULL,\n                    hired_at VARCHAR(64) NOT NULL,\n                    ended_at VARCHAR(64) NOT NULL,\n                    reason VARCHAR(24) NOT NULL DEFAULT 'quit',\n                    PRIMARY KEY (id),\n                    KEY idx_career_history_user (guild_id, user_id, ended_at)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_career_employment_city ON career_employment(guild_id,city_key,career_key)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_career_history_user ON career_history(guild_id,user_id,ended_at)')

