from __future__ import annotations
from app.database_support import *

class DatabaseMixin7Part4:

    async def _initialize_part_4(self, db) -> None:
        faction_schema = ('CREATE TABLE IF NOT EXISTS crew_perks (\n                    guild_id INTEGER NOT NULL, crew_id INTEGER NOT NULL, perk_key TEXT NOT NULL, rank INTEGER NOT NULL DEFAULT 0,\n                    PRIMARY KEY (guild_id,crew_id,perk_key)\n                )', "CREATE TABLE IF NOT EXISTS crew_custom_ranks (\n                    rank_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, crew_id INTEGER NOT NULL,\n                    name TEXT NOT NULL, position INTEGER NOT NULL DEFAULT 0, permissions_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL,\n                    UNIQUE (guild_id,crew_id,name)\n                )", 'CREATE TABLE IF NOT EXISTS crew_member_custom_ranks (\n                    guild_id INTEGER NOT NULL, crew_id INTEGER NOT NULL, user_id INTEGER NOT NULL, rank_id INTEGER NOT NULL,\n                    PRIMARY KEY (guild_id,crew_id,user_id)\n                )', "CREATE TABLE IF NOT EXISTS crew_wars (\n                    war_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, challenger_crew_id INTEGER NOT NULL,\n                    target_crew_id INTEGER NOT NULL, objective_id TEXT NOT NULL, stat TEXT NOT NULL, target INTEGER NOT NULL,\n                    challenger_score INTEGER NOT NULL DEFAULT 0, target_score INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'pending',\n                    winner_crew_id INTEGER, created_by INTEGER NOT NULL, created_at TEXT NOT NULL, accepted_at TEXT, expires_at TEXT NOT NULL, resolved_at TEXT\n                )", 'CREATE INDEX IF NOT EXISTS idx_crew_wars_active ON crew_wars(guild_id,status,expires_at)')
        for statement in faction_schema:
            await db.execute(statement)
        business_schema = ('CREATE TABLE IF NOT EXISTS business_licenses (\n                    guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL, purchased_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id,user_id)\n                )', "CREATE TABLE IF NOT EXISTS business_properties (\n                    property_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, template_key TEXT NOT NULL,\n                    name TEXT NOT NULL, emoji TEXT NOT NULL DEFAULT '🏢', category TEXT NOT NULL, city TEXT NOT NULL, district TEXT NOT NULL, street TEXT NOT NULL,\n                    base_price INTEGER NOT NULL, base_hourly_revenue INTEGER NOT NULL, hourly_upkeep INTEGER NOT NULL, max_workers INTEGER NOT NULL DEFAULT 2,\n                    owner_id INTEGER, level INTEGER NOT NULL DEFAULT 1, reputation INTEGER NOT NULL DEFAULT 0, last_claim_at TEXT, acquired_at TEXT, created_at TEXT NOT NULL,\n                    UNIQUE (guild_id,template_key)\n                )", 'CREATE INDEX IF NOT EXISTS idx_business_properties_owner ON business_properties(guild_id,owner_id,base_price)', 'CREATE TABLE IF NOT EXISTS business_workers (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, property_id INTEGER NOT NULL, owner_id INTEGER NOT NULL,\n                    worker_key TEXT NOT NULL, name TEXT NOT NULL, tier TEXT NOT NULL, revenue_bonus_percent INTEGER NOT NULL, wage_per_hour INTEGER NOT NULL,\n                    hired_at TEXT NOT NULL, expires_at TEXT NOT NULL\n                )', 'CREATE INDEX IF NOT EXISTS idx_business_workers_property ON business_workers(guild_id,property_id,expires_at)', "CREATE TABLE IF NOT EXISTS business_offers (\n                    offer_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, property_id INTEGER NOT NULL, seller_id INTEGER NOT NULL, buyer_id INTEGER NOT NULL,\n                    amount INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, expires_at TEXT NOT NULL, resolved_at TEXT\n                )", 'CREATE INDEX IF NOT EXISTS idx_business_offers_active ON business_offers(guild_id,status,expires_at)', 'CREATE INDEX IF NOT EXISTS idx_business_offers_property ON business_offers(guild_id,property_id,status,offer_id)', 'CREATE INDEX IF NOT EXISTS idx_business_offers_buyer ON business_offers(guild_id,buyer_id,status,expires_at)', 'CREATE TABLE IF NOT EXISTS business_transactions (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, property_id INTEGER NOT NULL, user_id INTEGER NOT NULL,\n                    amount INTEGER NOT NULL, kind TEXT NOT NULL, created_at TEXT NOT NULL\n                )', 'CREATE INDEX IF NOT EXISTS idx_business_transactions_guild ON business_transactions(guild_id,created_at DESC)')
        for statement in business_schema:
            await db.execute(statement)
        heist_schema = ("CREATE TABLE IF NOT EXISTS heist_lobbies (\n                    lobby_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, leader_id INTEGER NOT NULL,\n                    target_key TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'forming', phase INTEGER NOT NULL DEFAULT 0,\n                    created_at TEXT NOT NULL, expires_at TEXT NOT NULL, started_at TEXT, resolved_at TEXT\n                )", 'CREATE INDEX IF NOT EXISTS idx_heist_lobbies_active ON heist_lobbies(guild_id,status,expires_at)', 'CREATE INDEX IF NOT EXISTS idx_heist_lobbies_leader ON heist_lobbies(guild_id,leader_id,status,expires_at)', "CREATE TABLE IF NOT EXISTS heist_lobby_members (\n                    guild_id INTEGER NOT NULL, lobby_id INTEGER NOT NULL, user_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending',\n                    role_key TEXT NOT NULL DEFAULT 'support', cut_percent INTEGER NOT NULL DEFAULT 0, cut_accepted INTEGER NOT NULL DEFAULT 0,\n                    gear_key TEXT, joined_at TEXT NOT NULL, PRIMARY KEY (guild_id,lobby_id,user_id)\n                )", 'CREATE INDEX IF NOT EXISTS idx_heist_members_user ON heist_lobby_members(guild_id,user_id,status,lobby_id)', "CREATE TABLE IF NOT EXISTS heist_runs (\n                    run_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, lobby_id INTEGER NOT NULL, target_key TEXT NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'running', phase INTEGER NOT NULL DEFAULT 0, reward_pool INTEGER NOT NULL DEFAULT 0,\n                    phase_results TEXT NOT NULL DEFAULT '[]', member_snapshot TEXT NOT NULL DEFAULT '{}', success INTEGER, total_reward INTEGER NOT NULL DEFAULT 0,\n                    started_at TEXT NOT NULL, resolved_at TEXT\n                )", 'CREATE INDEX IF NOT EXISTS idx_heist_runs_history ON heist_runs(guild_id,status,resolved_at)', 'CREATE INDEX IF NOT EXISTS idx_heist_runs_lobby ON heist_runs(guild_id,lobby_id,status)', 'CREATE TABLE IF NOT EXISTS heist_gear (\n                    guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL, gear_key TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 0,\n                    PRIMARY KEY (guild_id,user_id,gear_key)\n                )', 'CREATE TABLE IF NOT EXISTS heist_cooldowns (\n                    guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL, last_heist_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id,user_id)\n                )')
        for statement in heist_schema:
            await db.execute(statement)
        legacy_stat_map = {'work.count': 'work_count', 'crime.success': 'crime_success', 'crime.fail': 'crime_failed', 'rob.success': 'rob_success', 'rob.fail': 'rob_failed', 'rob.profit': 'rob_profit', 'gambling.profit': 'gambling_profit', 'gambling.wins': 'game_wins', 'beg.count': 'beg_count', 'search.count': 'search_count', 'economy.earned': 'money_earned', 'economy.lost': 'money_lost', 'weekly.count': 'weekly_count', 'monthly.count': 'monthly_count', 'scratch.count': 'scratch_count', 'gambling.chickenfight.wins': 'chicken_wins', 'community.jackpot.wins': 'jackpot_wins', 'community.lottery.wins': 'lottery_wins'}
        stat_now = datetime.now(timezone.utc).isoformat()
        for stat_name, column in legacy_stat_map.items():
            await db.execute(f'INSERT OR IGNORE INTO user_statistics\n                        (guild_id, user_id, stat_name, value, updated_at)\n                        SELECT guild_id, user_id, ?, {column}, ? FROM users', (stat_name, stat_now))
