from __future__ import annotations
from app.database_support import *

class DatabaseMixin7Part7:

    async def _initialize_part_7(self, db) -> None:
        await db.execute("CREATE TABLE IF NOT EXISTS betting_matches (\n                    match_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL,\n                    cycle_key TEXT NOT NULL, league TEXT NOT NULL, home TEXT NOT NULL, away TEXT NOT NULL,\n                    home_rating INTEGER NOT NULL, away_rating INTEGER NOT NULL, kickoff_at TEXT NOT NULL,\n                    odds_json TEXT NOT NULL, seed TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open',\n                    home_score INTEGER, away_score INTEGER, ht_home INTEGER, ht_away INTEGER, settled_at TEXT,\n                    UNIQUE(guild_id,cycle_key,league,home,away)\n                )")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_betting_matches_cycle ON betting_matches(guild_id,cycle_key,kickoff_at)')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_betting_matches_due ON betting_matches(guild_id,status,kickoff_at)')
        await db.execute('CREATE TABLE IF NOT EXISTS betting_draft_legs (\n                    guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL, match_id INTEGER NOT NULL,\n                    market_key TEXT NOT NULL, selection_key TEXT NOT NULL, label TEXT NOT NULL, odds REAL NOT NULL,\n                    added_at TEXT NOT NULL, PRIMARY KEY(guild_id,user_id,match_id),\n                    FOREIGN KEY(match_id) REFERENCES betting_matches(match_id) ON DELETE CASCADE\n                )')
        await db.execute("CREATE TABLE IF NOT EXISTS betting_tickets (\n                    ticket_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL,\n                    bet_type TEXT NOT NULL, system_k INTEGER, stake_unit INTEGER NOT NULL, total_stake INTEGER NOT NULL,\n                    combined_odds REAL NOT NULL DEFAULT 1, potential_payout INTEGER NOT NULL DEFAULT 0,\n                    payout INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'open',\n                    created_at TEXT NOT NULL, settled_at TEXT\n                )")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_betting_tickets_user ON betting_tickets(guild_id,user_id,created_at DESC)')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_betting_tickets_open ON betting_tickets(guild_id,status,ticket_id)')
        await db.execute("CREATE TABLE IF NOT EXISTS betting_ticket_legs (\n                    ticket_id INTEGER NOT NULL, leg_index INTEGER NOT NULL, match_id INTEGER NOT NULL,\n                    market_key TEXT NOT NULL, selection_key TEXT NOT NULL, label TEXT NOT NULL, odds REAL NOT NULL,\n                    result TEXT NOT NULL DEFAULT 'pending', PRIMARY KEY(ticket_id,leg_index),\n                    FOREIGN KEY(ticket_id) REFERENCES betting_tickets(ticket_id) ON DELETE CASCADE,\n                    FOREIGN KEY(match_id) REFERENCES betting_matches(match_id) ON DELETE RESTRICT\n                )")
        await db.execute("CREATE TABLE IF NOT EXISTS horse_races (\n                    race_id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id INTEGER NOT NULL, race_key TEXT NOT NULL,\n                    starts_at TEXT NOT NULL, closes_at TEXT NOT NULL, horses_json TEXT NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'open', result_json TEXT, settled_at TEXT,\n                    UNIQUE(guild_id,race_key)\n                )")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_horse_races_due ON horse_races(guild_id,status,starts_at)')
        await db.execute("CREATE TABLE IF NOT EXISTS horse_bets (\n                    bet_id INTEGER PRIMARY KEY AUTOINCREMENT, race_id INTEGER NOT NULL, guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL,\n                    horse_index INTEGER NOT NULL, market TEXT NOT NULL, odds REAL NOT NULL, stake INTEGER NOT NULL,\n                    payout INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL, settled_at TEXT,\n                    FOREIGN KEY(race_id) REFERENCES horse_races(race_id) ON DELETE CASCADE\n                )")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_horse_bets_user ON horse_bets(guild_id,user_id,created_at DESC)')
        await db.execute("CREATE TABLE IF NOT EXISTS live_game_sessions (\n                    session_id TEXT PRIMARY KEY, guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL,\n                    game TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', stake INTEGER NOT NULL DEFAULT 0,\n                    reward INTEGER NOT NULL DEFAULT 0, stage INTEGER NOT NULL DEFAULT 0, data_json TEXT NOT NULL DEFAULT '{}',\n                    created_at TEXT NOT NULL, updated_at TEXT NOT NULL, finished_at TEXT\n                )")
        await db.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_live_game_active_user ON live_game_sessions(guild_id,user_id) WHERE status='active'")
        await db.execute("CREATE TABLE IF NOT EXISTS poker_tables (\n                    table_id TEXT PRIMARY KEY, guild_id INTEGER NOT NULL, channel_id INTEGER NOT NULL, message_id INTEGER,\n                    owner_id INTEGER NOT NULL, buy_in INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'lobby',\n                    created_at TEXT NOT NULL, updated_at TEXT NOT NULL, finished_at TEXT\n                )")
        await db.execute("CREATE TABLE IF NOT EXISTS poker_players (\n                    table_id TEXT NOT NULL, user_id INTEGER NOT NULL, seat INTEGER NOT NULL, reserved INTEGER NOT NULL DEFAULT 0,\n                    payout INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'joined',\n                    PRIMARY KEY(table_id,user_id), FOREIGN KEY(table_id) REFERENCES poker_tables(table_id) ON DELETE CASCADE\n                )")
