from __future__ import annotations
from app.database_support import *

class DatabaseMixin5Part2:

    async def _ensure_contract_economy_schema_part_2(self, db: aiosqlite.Connection) -> None:
        await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS contract_history (\n                    history_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    contract_id INTEGER NOT NULL,\n                    event_key TEXT NOT NULL,\n                    event_type TEXT NOT NULL,\n                    actor_id INTEGER,\n                    metadata_json TEXT NOT NULL DEFAULT '{}',\n                    created_at TEXT NOT NULL,\n                    UNIQUE(guild_id,contract_id,event_key),\n                    FOREIGN KEY (contract_id) REFERENCES contracts(contract_id) ON DELETE CASCADE\n                )\n            ", mysql_sql='\n                CREATE TABLE IF NOT EXISTS contract_history (\n                    history_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    contract_id BIGINT UNSIGNED NOT NULL,\n                    event_key VARCHAR(190) NOT NULL,\n                    event_type VARCHAR(40) NOT NULL,\n                    actor_id BIGINT UNSIGNED NULL,\n                    metadata_json LONGTEXT NOT NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (history_id),\n                    UNIQUE KEY uq_contract_history_event (guild_id,contract_id,event_key),\n                    KEY idx_contract_history_contract (guild_id,contract_id,history_id),\n                    CONSTRAINT fk_contract_history_contract\n                        FOREIGN KEY (contract_id) REFERENCES contracts (contract_id)\n                        ON UPDATE CASCADE ON DELETE CASCADE\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
        await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS contract_event_claims (\n                    guild_id INTEGER NOT NULL,\n                    event_key TEXT NOT NULL,\n                    contract_id INTEGER NOT NULL,\n                    event_type TEXT NOT NULL,\n                    actor_id INTEGER NOT NULL,\n                    created_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id,event_key),\n                    FOREIGN KEY (contract_id) REFERENCES contracts(contract_id) ON DELETE CASCADE\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS contract_event_claims (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    event_key VARCHAR(190) NOT NULL,\n                    contract_id BIGINT UNSIGNED NOT NULL,\n                    event_type VARCHAR(40) NOT NULL,\n                    actor_id BIGINT UNSIGNED NOT NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id,event_key),\n                    KEY idx_contract_event_claim_contract (guild_id,contract_id),\n                    CONSTRAINT fk_contract_event_claim_contract\n                        FOREIGN KEY (contract_id) REFERENCES contracts (contract_id)\n                        ON UPDATE CASCADE ON DELETE CASCADE\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
        await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS item_transfer_history (\n                    transfer_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    sender_id INTEGER NOT NULL,\n                    receiver_id INTEGER NOT NULL,\n                    item_id TEXT NOT NULL,\n                    quantity INTEGER NOT NULL,\n                    source_ref TEXT NOT NULL,\n                    created_at TEXT NOT NULL,\n                    UNIQUE(guild_id,source_ref)\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS item_transfer_history (\n                    transfer_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    sender_id BIGINT UNSIGNED NOT NULL,\n                    receiver_id BIGINT UNSIGNED NOT NULL,\n                    item_id VARCHAR(64) NOT NULL,\n                    quantity DECIMAL(65,0) NOT NULL,\n                    source_ref VARCHAR(190) NOT NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (transfer_id),\n                    UNIQUE KEY uq_item_transfer_source (guild_id,source_ref),\n                    KEY idx_item_transfer_users (guild_id,sender_id,receiver_id,transfer_id)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
