from __future__ import annotations
from app.database_support import *

class DatabaseMixin7Part2:

    async def _initialize_part_2(self, db) -> None:
        await db.execute('\n                CREATE TABLE IF NOT EXISTS shop_items (\n                    item_id TEXT PRIMARY KEY,\n                    name TEXT NOT NULL,\n                    description TEXT NOT NULL,\n                    price INTEGER NOT NULL,\n                    emoji TEXT NOT NULL,\n                    active INTEGER NOT NULL DEFAULT 1\n                )\n                ')
        await db.execute('\n                CREATE TABLE IF NOT EXISTS inventory (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    item_id TEXT NOT NULL,\n                    quantity INTEGER NOT NULL DEFAULT 0,\n                    PRIMARY KEY (guild_id, user_id, item_id),\n                    FOREIGN KEY (item_id) REFERENCES shop_items(item_id)\n                )\n                ')
        await db.execute('CREATE TABLE IF NOT EXISTS achievements (\n                    guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL, achievement_id TEXT NOT NULL,\n                    unlocked_at TEXT NOT NULL, PRIMARY KEY (guild_id, user_id, achievement_id)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS user_badges (\n                    guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL, badge_id TEXT NOT NULL,\n                    unlocked_at TEXT NOT NULL, PRIMARY KEY (guild_id, user_id, badge_id)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS lottery_history (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    winner_id INTEGER NOT NULL,\n                    total_tickets INTEGER NOT NULL,\n                    payout INTEGER NOT NULL,\n                    drawn_at TEXT NOT NULL\n                )')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_lottery_history_guild ON lottery_history(guild_id,id DESC)')
        await db.execute('CREATE TABLE IF NOT EXISTS lottery_entries (\n                    guild_id INTEGER NOT NULL, user_id INTEGER NOT NULL, tickets INTEGER NOT NULL DEFAULT 0,\n                    PRIMARY KEY (guild_id, user_id)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS guild_state (\n                    guild_id INTEGER NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, key)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS market_daily (\n                    guild_id INTEGER NOT NULL,\n                    item_id TEXT NOT NULL,\n                    market_date TEXT NOT NULL,\n                    price INTEGER NOT NULL,\n                    stock INTEGER NOT NULL,\n                    starting_stock INTEGER NOT NULL,\n                    PRIMARY KEY (guild_id, item_id, market_date)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS user_statistics (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    stat_name TEXT NOT NULL,\n                    value INTEGER NOT NULL DEFAULT 0,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id, stat_name)\n                )')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_user_statistics_lookup ON user_statistics(guild_id, stat_name, value DESC)')
        await db.execute('CREATE TABLE IF NOT EXISTS activity_users (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    total_xp INTEGER NOT NULL DEFAULT 0,\n                    chat_xp INTEGER NOT NULL DEFAULT 0,\n                    voice_xp INTEGER NOT NULL DEFAULT 0,\n                    message_count INTEGER NOT NULL DEFAULT 0,\n                    voice_seconds INTEGER NOT NULL DEFAULT 0,\n                    level INTEGER NOT NULL DEFAULT 0,\n                    last_chat_xp_at TEXT,\n                    last_message_at TEXT,\n                    last_message_hash TEXT,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id)\n                )')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_activity_level ON activity_users(guild_id, level DESC, total_xp DESC)')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_activity_chat ON activity_users(guild_id, message_count DESC, chat_xp DESC)')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_activity_voice ON activity_users(guild_id, voice_seconds DESC, voice_xp DESC)')
        await db.execute('CREATE TABLE IF NOT EXISTS activity_message_hashes (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    message_hash TEXT NOT NULL,\n                    last_seen TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id, message_hash)\n                )')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_activity_message_hash_seen ON activity_message_hashes(guild_id,user_id,last_seen)')
        await db.execute("CREATE TABLE IF NOT EXISTS job_sessions (\n                    session_id TEXT PRIMARY KEY,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    job TEXT NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    stage INTEGER NOT NULL DEFAULT 1,\n                    score INTEGER NOT NULL DEFAULT 50,\n                    reward INTEGER NOT NULL DEFAULT 0,\n                    data_json TEXT NOT NULL DEFAULT '{}',\n                    created_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    finished_at TEXT\n                )")
        await db.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_job_active_user ON job_sessions(guild_id,user_id) WHERE status='active'")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_job_sessions_history ON job_sessions(guild_id,user_id,created_at DESC)')
        await db.execute("CREATE TABLE IF NOT EXISTS job_mastery (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    job TEXT NOT NULL,\n                    xp INTEGER NOT NULL DEFAULT 0,\n                    level INTEGER NOT NULL DEFAULT 1,\n                    shifts INTEGER NOT NULL DEFAULT 0,\n                    best_rating TEXT NOT NULL DEFAULT 'D',\n                    total_earned INTEGER NOT NULL DEFAULT 0,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY(guild_id,user_id,job)\n                )")
        await db.execute('CREATE TABLE IF NOT EXISTS job_history (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    job TEXT NOT NULL,\n                    score INTEGER NOT NULL,\n                    rating TEXT NOT NULL,\n                    reward INTEGER NOT NULL,\n                    mastery_xp INTEGER NOT NULL,\n                    created_at TEXT NOT NULL\n                )')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_job_history_user ON job_history(guild_id,user_id,created_at DESC)')
