from __future__ import annotations
from app.database_support import *

class DatabaseMixin7Part5:

    async def _initialize_part_5(self, db) -> None:
        await db.execute('CREATE TABLE IF NOT EXISTS moderation_warnings (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    moderator_id INTEGER NOT NULL,\n                    reason TEXT NOT NULL,\n                    created_at TEXT NOT NULL\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS moderation_cases (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    action TEXT NOT NULL,\n                    target_id INTEGER NOT NULL,\n                    moderator_id INTEGER NOT NULL,\n                    reason TEXT NOT NULL,\n                    created_at TEXT NOT NULL\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS automod_rules (\n                    guild_id INTEGER NOT NULL,\n                    rule TEXT NOT NULL,\n                    enabled INTEGER NOT NULL,\n                    action TEXT NOT NULL,\n                    threshold INTEGER NOT NULL,\n                    timeout_seconds INTEGER NOT NULL,\n                    PRIMARY KEY (guild_id, rule)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS automod_exemptions (\n                    guild_id INTEGER NOT NULL,\n                    rule TEXT NOT NULL,\n                    scope_type TEXT NOT NULL,\n                    scope_id INTEGER NOT NULL,\n                    PRIMARY KEY (guild_id, rule, scope_type, scope_id)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS automod_domains (\n                    guild_id INTEGER NOT NULL,\n                    mode TEXT NOT NULL,\n                    domain TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, mode, domain)\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS automod_words (\n                    guild_id INTEGER NOT NULL,\n                    word TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, word)\n                )')
        await db.execute("CREATE TABLE IF NOT EXISTS role_panels (\n                    panel_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    channel_id INTEGER NOT NULL,\n                    message_id INTEGER,\n                    title TEXT NOT NULL,\n                    description TEXT NOT NULL DEFAULT '',\n                    mode TEXT NOT NULL DEFAULT 'toggle',\n                    active INTEGER NOT NULL DEFAULT 1,\n                    created_by INTEGER NOT NULL,\n                    created_at TEXT NOT NULL\n                )")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_role_panels_guild ON role_panels(guild_id, active, panel_id)')
        await db.execute('CREATE TABLE IF NOT EXISTS role_panel_items (\n                    panel_id INTEGER NOT NULL,\n                    role_id INTEGER NOT NULL,\n                    label TEXT NOT NULL,\n                    emoji TEXT,\n                    position INTEGER NOT NULL DEFAULT 0,\n                    PRIMARY KEY (panel_id, role_id),\n                    FOREIGN KEY (panel_id) REFERENCES role_panels(panel_id) ON DELETE CASCADE\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS verification_panels (\n                    guild_id INTEGER PRIMARY KEY,\n                    channel_id INTEGER NOT NULL,\n                    message_id INTEGER,\n                    role_id INTEGER NOT NULL,\n                    remove_role_id INTEGER,\n                    title TEXT NOT NULL,\n                    body TEXT NOT NULL,\n                    button_label TEXT NOT NULL,\n                    active INTEGER NOT NULL DEFAULT 1\n                )')
        await db.execute('CREATE TABLE IF NOT EXISTS member_role_snapshots (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    role_ids TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id)\n                )')
        await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                    CREATE TABLE IF NOT EXISTS user_badge_showcase (\n                        guild_id INTEGER NOT NULL,\n                        user_id INTEGER NOT NULL,\n                        slot_index INTEGER NOT NULL,\n                        badge_id TEXT NOT NULL,\n                        updated_at TEXT NOT NULL,\n                        PRIMARY KEY (guild_id,user_id,slot_index),\n                        UNIQUE (guild_id,user_id,badge_id)\n                    )\n                ', mysql_sql='\n                    CREATE TABLE IF NOT EXISTS user_badge_showcase (\n                        guild_id BIGINT UNSIGNED NOT NULL,\n                        user_id BIGINT UNSIGNED NOT NULL,\n                        slot_index TINYINT UNSIGNED NOT NULL,\n                        badge_id VARCHAR(64) NOT NULL,\n                        updated_at VARCHAR(64) NOT NULL,\n                        PRIMARY KEY (guild_id,user_id,slot_index),\n                        UNIQUE KEY uq_user_badge_showcase_badge (guild_id,user_id,badge_id)\n                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n                ')
        await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                    CREATE TABLE IF NOT EXISTS player_notification_preferences (\n                        guild_id INTEGER NOT NULL,\n                        user_id INTEGER NOT NULL,\n                        category TEXT NOT NULL,\n                        dm_enabled INTEGER NOT NULL DEFAULT 1,\n                        updated_at TEXT NOT NULL,\n                        PRIMARY KEY (guild_id,user_id,category)\n                    )\n                ', mysql_sql='\n                    CREATE TABLE IF NOT EXISTS player_notification_preferences (\n                        guild_id BIGINT UNSIGNED NOT NULL,\n                        user_id BIGINT UNSIGNED NOT NULL,\n                        category VARCHAR(64) NOT NULL,\n                        dm_enabled TINYINT(1) NOT NULL DEFAULT 1,\n                        updated_at VARCHAR(64) NOT NULL,\n                        PRIMARY KEY (guild_id,user_id,category)\n                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n                ')
        await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                    CREATE TABLE IF NOT EXISTS player_notifications (\n                        notification_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                        guild_id INTEGER NOT NULL,\n                        user_id INTEGER NOT NULL,\n                        category TEXT NOT NULL,\n                        severity TEXT NOT NULL,\n                        event_key TEXT NOT NULL,\n                        title TEXT NOT NULL,\n                        body TEXT NOT NULL,\n                        action_type TEXT,\n                        action_ref TEXT,\n                        action_label TEXT,\n                        created_at TEXT NOT NULL,\n                        expires_at TEXT,\n                        read_at TEXT,\n                        dm_status TEXT NOT NULL DEFAULT 'pending',\n                        dm_sent_at TEXT,\n                        UNIQUE(guild_id,user_id,event_key)\n                    )\n                ", mysql_sql="\n                    CREATE TABLE IF NOT EXISTS player_notifications (\n                        notification_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                        guild_id BIGINT UNSIGNED NOT NULL,\n                        user_id BIGINT UNSIGNED NOT NULL,\n                        category VARCHAR(64) NOT NULL,\n                        severity VARCHAR(32) NOT NULL,\n                        event_key VARCHAR(191) NOT NULL,\n                        title VARCHAR(255) NOT NULL,\n                        body LONGTEXT NOT NULL,\n                        action_type VARCHAR(64) NULL,\n                        action_ref VARCHAR(255) NULL,\n                        action_label VARCHAR(128) NULL,\n                        created_at VARCHAR(64) NOT NULL,\n                        expires_at VARCHAR(64) NULL,\n                        read_at VARCHAR(64) NULL,\n                        dm_status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                        dm_sent_at VARCHAR(64) NULL,\n                        PRIMARY KEY (notification_id),\n                        UNIQUE KEY uq_player_notifications_event (guild_id,user_id,event_key),\n                        KEY idx_player_notifications_inbox (guild_id,user_id,read_at,notification_id)\n                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n                ")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_player_notifications_inbox ON player_notifications(guild_id,user_id,read_at,notification_id)')
