from __future__ import annotations
from app.database_support import *

class DatabaseMixin7Part1:

    async def _initialize_part_1(self, db) -> None:
        await self._validate_mysql_cutover(db)
        await db.execute('PRAGMA journal_mode=WAL;')
        await db.execute('PRAGMA foreign_keys=ON;')
        await db.execute('\n                CREATE TABLE IF NOT EXISTS users (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    wallet INTEGER NOT NULL DEFAULT 0,\n                    bank INTEGER NOT NULL DEFAULT 0,\n                    created_at TEXT NOT NULL,\n                    last_work TEXT,\n                    PRIMARY KEY (guild_id, user_id)\n                )\n                ')
        for name, definition in [('last_beg', 'TEXT'), ('last_search', 'TEXT'), ('last_slut', 'TEXT'), ('last_crime', 'TEXT'), ('last_rob', 'TEXT'), ('work_count', 'INTEGER NOT NULL DEFAULT 0'), ('crime_success', 'INTEGER NOT NULL DEFAULT 0'), ('crime_failed', 'INTEGER NOT NULL DEFAULT 0'), ('rob_success', 'INTEGER NOT NULL DEFAULT 0'), ('rob_failed', 'INTEGER NOT NULL DEFAULT 0'), ('rob_profit', 'INTEGER NOT NULL DEFAULT 0'), ('gambling_profit', 'INTEGER NOT NULL DEFAULT 0'), ('game_wins', 'INTEGER NOT NULL DEFAULT 0'), ('beg_count', 'INTEGER NOT NULL DEFAULT 0'), ('search_count', 'INTEGER NOT NULL DEFAULT 0'), ('money_earned', 'INTEGER NOT NULL DEFAULT 0'), ('money_lost', 'INTEGER NOT NULL DEFAULT 0'), ('jail_until', 'TEXT'), ('last_weekly', 'TEXT'), ('last_monthly', 'TEXT'), ('last_interest', 'TEXT'), ('weekly_count', 'INTEGER NOT NULL DEFAULT 0'), ('monthly_count', 'INTEGER NOT NULL DEFAULT 0'), ('scratch_count', 'INTEGER NOT NULL DEFAULT 0'), ('chicken_wins', 'INTEGER NOT NULL DEFAULT 0'), ('selected_title', "TEXT NOT NULL DEFAULT 'Kezdő'"), ('last_withdraw', 'TEXT'), ('jackpot_wins', 'INTEGER NOT NULL DEFAULT 0'), ('lottery_wins', 'INTEGER NOT NULL DEFAULT 0')]:
            await self._ensure_user_column(db, name, definition)
        await db.execute('\n                CREATE TABLE IF NOT EXISTS transactions (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    amount INTEGER NOT NULL,\n                    reason TEXT NOT NULL,\n                    created_at TEXT NOT NULL\n                )\n                ')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_transactions_guild_created ON transactions(guild_id, created_at DESC)')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_transactions_user_created ON transactions(guild_id, user_id, created_at DESC)')
        await db.execute("\n                CREATE TABLE IF NOT EXISTS casino_sessions (\n                    game_id TEXT PRIMARY KEY,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    game TEXT NOT NULL,\n                    status TEXT NOT NULL,\n                    bet INTEGER NOT NULL,\n                    payout INTEGER NOT NULL DEFAULT 0,\n                    profit INTEGER NOT NULL DEFAULT 0,\n                    multiplier REAL NOT NULL DEFAULT 0,\n                    result TEXT NOT NULL DEFAULT '',\n                    config_json TEXT NOT NULL DEFAULT '{}',\n                    wallet_after INTEGER,\n                    created_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    settled_at TEXT\n                )\n                ")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_casino_sessions_user_created ON casino_sessions(guild_id, user_id, created_at DESC)')
        await db.execute('CREATE INDEX IF NOT EXISTS idx_casino_sessions_status ON casino_sessions(status, updated_at)')
        await db.execute("\n                CREATE TABLE IF NOT EXISTS casino_ledger (\n                    id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    game_id TEXT NOT NULL,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    entry_type TEXT NOT NULL,\n                    entry_key TEXT,\n                    amount INTEGER NOT NULL,\n                    balance_after INTEGER,\n                    metadata_json TEXT NOT NULL DEFAULT '{}',\n                    created_at TEXT NOT NULL,\n                    FOREIGN KEY (game_id) REFERENCES casino_sessions(game_id) ON DELETE CASCADE,\n                    UNIQUE(game_id, entry_key)\n                )\n                ")
        await db.execute('CREATE INDEX IF NOT EXISTS idx_casino_ledger_game ON casino_ledger(game_id, id)')
        await db.execute('\n                CREATE TABLE IF NOT EXISTS casino_monthly_jackpot (\n                    guild_id INTEGER NOT NULL,\n                    month TEXT NOT NULL,\n                    pool INTEGER NOT NULL DEFAULT 0,\n                    total_house_loss INTEGER NOT NULL DEFAULT 0,\n                    total_contributed INTEGER NOT NULL DEFAULT 0,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, month)\n                )\n                ')
        await db.execute('\n                CREATE TABLE IF NOT EXISTS casino_monthly_user_contrib (\n                    guild_id INTEGER NOT NULL,\n                    month TEXT NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    contributed INTEGER NOT NULL DEFAULT 0,\n                    house_loss INTEGER NOT NULL DEFAULT 0,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, month, user_id)\n                )\n                ')
        await db.execute("\n                CREATE TABLE IF NOT EXISTS casino_jackpot_history (\n                    guild_id INTEGER NOT NULL,\n                    month TEXT NOT NULL,\n                    pool INTEGER NOT NULL DEFAULT 0,\n                    payout INTEGER NOT NULL DEFAULT 0,\n                    winner_id INTEGER,\n                    eligible_players INTEGER NOT NULL DEFAULT 0,\n                    total_house_loss INTEGER NOT NULL DEFAULT 0,\n                    total_contributed INTEGER NOT NULL DEFAULT 0,\n                    outcome TEXT NOT NULL DEFAULT 'draw',\n                    drawn_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, month)\n                )\n                ")
