from __future__ import annotations
from app.database_support import *

class DatabaseMixin2:
        async def _ensure_housing_foundation_schema(self, db: aiosqlite.Connection) -> None:
            """Install the additive City + Housing V2 schema on both backends.

            ``housing_state`` remains the active-residence source of truth. V2 adds
            persistent owned properties, an independent home storage and garage
            assignments. All DDL is additive/idempotent; production data is never
            dropped or rewritten during normal startup.
            """
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS housing_state (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    tier_key TEXT NOT NULL DEFAULT 'street',\n                    city_key TEXT NOT NULL,\n                    acquired_at TEXT,\n                    paid_until TEXT,\n                    grace_until TEXT,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS housing_state (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    tier_key VARCHAR(24) NOT NULL DEFAULT 'street',\n                    city_key VARCHAR(32) NOT NULL,\n                    acquired_at VARCHAR(64) NULL,\n                    paid_until VARCHAR(64) NULL,\n                    grace_until VARCHAR(64) NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    KEY idx_housing_due (tier_key, paid_until),\n                    KEY idx_housing_city (guild_id, city_key, tier_key),\n                    CONSTRAINT fk_housing_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS housing_properties (\n                    property_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    city_key TEXT NOT NULL,\n                    tier_key TEXT NOT NULL,\n                    purchase_price INTEGER NOT NULL DEFAULT 0,\n                    maintenance_paid_until TEXT NOT NULL,\n                    maintenance_grace_until TEXT,\n                    maintenance_debt INTEGER NOT NULL DEFAULT 0,\n                    last_opportunity_cycle TEXT,\n                    status TEXT NOT NULL DEFAULT 'owned',\n                    acquired_at TEXT NOT NULL,\n                    upgraded_at TEXT,\n                    updated_at TEXT NOT NULL,\n                    sold_at TEXT,\n                    sale_price INTEGER,\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS housing_properties (\n                    property_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    city_key VARCHAR(32) NOT NULL,\n                    tier_key VARCHAR(24) NOT NULL,\n                    purchase_price DECIMAL(65,0) NOT NULL DEFAULT 0,\n                    maintenance_paid_until VARCHAR(64) NOT NULL,\n                    maintenance_grace_until VARCHAR(64) NULL,\n                    maintenance_debt DECIMAL(65,0) NOT NULL DEFAULT 0,\n                    last_opportunity_cycle VARCHAR(64) NULL,\n                    status VARCHAR(24) NOT NULL DEFAULT 'owned',\n                    acquired_at VARCHAR(64) NOT NULL,\n                    upgraded_at VARCHAR(64) NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    sold_at VARCHAR(64) NULL,\n                    sale_price DECIMAL(65,0) NULL,\n                    PRIMARY KEY (property_id),\n                    KEY idx_housing_properties_owner (guild_id, user_id, status, city_key),\n                    KEY idx_housing_properties_due (status, maintenance_paid_until),\n                    CONSTRAINT fk_housing_properties_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS housing_storage (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    item_id TEXT NOT NULL,\n                    quantity INTEGER NOT NULL DEFAULT 0,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id, item_id),\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS housing_storage (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    item_id VARCHAR(128) NOT NULL,\n                    quantity BIGINT NOT NULL DEFAULT 0,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, user_id, item_id),\n                    KEY idx_housing_storage_user (guild_id, user_id),\n                    CONSTRAINT fk_housing_storage_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS housing_garage (\n                    property_id INTEGER NOT NULL,\n                    vehicle_id INTEGER NOT NULL,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    parked_at TEXT NOT NULL,\n                    PRIMARY KEY (property_id, vehicle_id),\n                    UNIQUE (vehicle_id),\n                    FOREIGN KEY (property_id) REFERENCES housing_properties(property_id) ON DELETE CASCADE,\n                    FOREIGN KEY (vehicle_id) REFERENCES character_vehicles(vehicle_id) ON DELETE CASCADE\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS housing_garage (\n                    property_id BIGINT UNSIGNED NOT NULL,\n                    vehicle_id BIGINT UNSIGNED NOT NULL,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    parked_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (property_id, vehicle_id),\n                    UNIQUE KEY uq_housing_garage_vehicle (vehicle_id),\n                    KEY idx_housing_garage_owner (guild_id, user_id),\n                    CONSTRAINT fk_housing_garage_property\n                        FOREIGN KEY (property_id) REFERENCES housing_properties(property_id)\n                        ON UPDATE CASCADE ON DELETE CASCADE,\n                    CONSTRAINT fk_housing_garage_vehicle\n                        FOREIGN KEY (vehicle_id) REFERENCES character_vehicles(vehicle_id)\n                        ON UPDATE CASCADE ON DELETE CASCADE\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_housing_due ON housing_state(tier_key,paid_until)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_housing_city ON housing_state(guild_id,city_key,tier_key)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_housing_properties_owner ON housing_properties(guild_id,user_id,status,city_key)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_housing_properties_due ON housing_properties(status,maintenance_paid_until)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_housing_storage_user ON housing_storage(guild_id,user_id)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_housing_garage_owner ON housing_garage(guild_id,user_id)')

        async def _ensure_training_foundation_schema(self, db: aiosqlite.Connection) -> None:
            """Install the additive RP Training Center foundation schema."""
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS character_qualifications (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    qualification_key TEXT NOT NULL,\n                    course_key TEXT NOT NULL,\n                    acquired_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id, qualification_key),\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS character_qualifications (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    qualification_key VARCHAR(48) NOT NULL,\n                    course_key VARCHAR(48) NOT NULL,\n                    acquired_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, user_id, qualification_key),\n                    KEY idx_character_qualifications_course (guild_id, course_key),\n                    CONSTRAINT fk_character_qualifications_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS training_sessions (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    course_key TEXT NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    stage_index INTEGER NOT NULL DEFAULT 0,\n                    started_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    completed_at TEXT,\n                    PRIMARY KEY (guild_id, user_id, course_key),\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS training_sessions (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    course_key VARCHAR(48) NOT NULL,\n                    status VARCHAR(24) NOT NULL DEFAULT 'active',\n                    stage_index SMALLINT UNSIGNED NOT NULL DEFAULT 0,\n                    started_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    completed_at VARCHAR(64) NULL,\n                    PRIMARY KEY (guild_id, user_id, course_key),\n                    KEY idx_training_active (guild_id, user_id, status, updated_at),\n                    CONSTRAINT fk_training_sessions_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_qualifications_course ON character_qualifications(guild_id,course_key)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_training_active ON training_sessions(guild_id,user_id,status,updated_at)')

