from __future__ import annotations
from app.database_support import *

class DatabaseMixin4:
        async def _ensure_world_foundation_schema(self, db: aiosqlite.Connection) -> None:
            """Install the additive RP world-state foundation schema."""
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS rp_world_state (\n                    guild_id INTEGER NOT NULL PRIMARY KEY,\n                    cycle_id TEXT NOT NULL,\n                    national_key TEXT NOT NULL,\n                    city_events_json TEXT NOT NULL,\n                    started_at TEXT NOT NULL,\n                    expires_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS rp_world_state (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    cycle_id VARCHAR(32) NOT NULL,\n                    national_key VARCHAR(64) NOT NULL,\n                    city_events_json LONGTEXT NOT NULL,\n                    started_at VARCHAR(64) NOT NULL,\n                    expires_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id),\n                    KEY idx_rp_world_expiry (expires_at)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_rp_world_expiry ON rp_world_state(expires_at)')
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS rp_world_story_state (\n                    guild_id INTEGER NOT NULL PRIMARY KEY,\n                    story_key TEXT NOT NULL,\n                    beat_key TEXT NOT NULL,\n                    step_number INTEGER NOT NULL,\n                    started_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS rp_world_story_state (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    story_key VARCHAR(64) NOT NULL,\n                    beat_key VARCHAR(64) NOT NULL,\n                    step_number INT NOT NULL,\n                    started_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS rp_world_story_history (\n                    guild_id INTEGER NOT NULL,\n                    cycle_id TEXT NOT NULL,\n                    story_key TEXT NOT NULL,\n                    beat_key TEXT NOT NULL,\n                    step_number INTEGER NOT NULL,\n                    national_key TEXT NOT NULL,\n                    recorded_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, cycle_id)\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS rp_world_story_history (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    cycle_id VARCHAR(32) NOT NULL,\n                    story_key VARCHAR(64) NOT NULL,\n                    beat_key VARCHAR(64) NOT NULL,\n                    step_number INT NOT NULL,\n                    national_key VARCHAR(64) NOT NULL,\n                    recorded_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, cycle_id),\n                    KEY idx_rp_world_story_history (guild_id, story_key, recorded_at)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_rp_world_story_history ON rp_world_story_history(guild_id,story_key,recorded_at)')

        async def _ensure_memory_opportunity_schema(self, db: aiosqlite.Connection) -> None:
            """Install Phase 3 consequence-memory and opportunity-history state.

            ``character_history`` remains the player-facing life timeline.  These
            tables are machine-readable state for eligibility/pacing and therefore
            intentionally avoid duplicating history prose.
            """
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS character_memory_state (\n                    memory_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    memory_key TEXT NOT NULL,\n                    category TEXT NOT NULL,\n                    subject_type TEXT NOT NULL,\n                    subject_key TEXT NOT NULL,\n                    state_key TEXT NOT NULL,\n                    value_json TEXT NOT NULL DEFAULT '{}',\n                    active INTEGER NOT NULL DEFAULT 1,\n                    source_history_event_id INTEGER,\n                    occurred_at TEXT NOT NULL,\n                    expires_at TEXT,\n                    created_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    UNIQUE(guild_id,user_id,memory_key),\n                    FOREIGN KEY (guild_id,user_id) REFERENCES characters(guild_id,user_id) ON DELETE RESTRICT\n                )\n            ", mysql_sql='\n                CREATE TABLE IF NOT EXISTS character_memory_state (\n                    memory_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    memory_key VARCHAR(64) NOT NULL,\n                    category VARCHAR(24) NOT NULL,\n                    subject_type VARCHAR(24) NOT NULL,\n                    subject_key VARCHAR(64) NOT NULL,\n                    state_key VARCHAR(64) NOT NULL,\n                    value_json LONGTEXT NOT NULL,\n                    active TINYINT UNSIGNED NOT NULL DEFAULT 1,\n                    source_history_event_id BIGINT UNSIGNED NULL,\n                    occurred_at VARCHAR(64) NOT NULL,\n                    expires_at VARCHAR(64) NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (memory_id),\n                    UNIQUE KEY uq_character_memory_key (guild_id,user_id,memory_key),\n                    KEY idx_character_memory_subject (guild_id,user_id,subject_type,subject_key,active),\n                    KEY idx_character_memory_category (guild_id,user_id,category,active,occurred_at),\n                    CONSTRAINT fk_character_memory_character\n                        FOREIGN KEY (guild_id,user_id)\n                        REFERENCES characters (guild_id,user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS character_relationship_state (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    subject_type TEXT NOT NULL,\n                    subject_key TEXT NOT NULL,\n                    trust_score INTEGER NOT NULL DEFAULT 0,\n                    favor_owed_to_player INTEGER NOT NULL DEFAULT 0,\n                    favor_owed_by_player INTEGER NOT NULL DEFAULT 0,\n                    rival_state TEXT NOT NULL DEFAULT 'none',\n                    flags_json TEXT NOT NULL DEFAULT '{}',\n                    last_memory_key TEXT,\n                    created_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id,user_id,subject_type,subject_key),\n                    FOREIGN KEY (guild_id,user_id) REFERENCES characters(guild_id,user_id) ON DELETE RESTRICT\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS character_relationship_state (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    subject_type VARCHAR(24) NOT NULL,\n                    subject_key VARCHAR(64) NOT NULL,\n                    trust_score SMALLINT NOT NULL DEFAULT 0,\n                    favor_owed_to_player SMALLINT UNSIGNED NOT NULL DEFAULT 0,\n                    favor_owed_by_player SMALLINT UNSIGNED NOT NULL DEFAULT 0,\n                    rival_state VARCHAR(24) NOT NULL DEFAULT 'none',\n                    flags_json LONGTEXT NOT NULL,\n                    last_memory_key VARCHAR(64) NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id,user_id,subject_type,subject_key),\n                    KEY idx_character_relationship_rival (guild_id,user_id,rival_state,updated_at),\n                    CONSTRAINT fk_character_relationship_character\n                        FOREIGN KEY (guild_id,user_id)\n                        REFERENCES characters (guild_id,user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS player_opportunity_history (\n                    event_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    opportunity_key TEXT NOT NULL,\n                    source_family TEXT NOT NULL,\n                    action_key TEXT,\n                    cycle_id TEXT,\n                    event_type TEXT NOT NULL,\n                    created_at TEXT NOT NULL,\n                    FOREIGN KEY (guild_id,user_id) REFERENCES characters(guild_id,user_id) ON DELETE RESTRICT\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS player_opportunity_history (\n                    event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    opportunity_key VARCHAR(96) NOT NULL,\n                    source_family VARCHAR(32) NOT NULL,\n                    action_key VARCHAR(96) NULL,\n                    cycle_id VARCHAR(32) NULL,\n                    event_type VARCHAR(24) NOT NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (event_id),\n                    KEY idx_player_opportunity_user (guild_id,user_id,event_id),\n                    KEY idx_player_opportunity_key (guild_id,user_id,opportunity_key,event_type,event_id),\n                    CONSTRAINT fk_player_opportunity_character\n                        FOREIGN KEY (guild_id,user_id)\n                        REFERENCES characters (guild_id,user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_memory_subject ON character_memory_state(guild_id,user_id,subject_type,subject_key,active)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_memory_category ON character_memory_state(guild_id,user_id,category,active,occurred_at)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_relationship_rival ON character_relationship_state(guild_id,user_id,rival_state,updated_at)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_player_opportunity_user ON player_opportunity_history(guild_id,user_id,event_id)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_player_opportunity_key ON player_opportunity_history(guild_id,user_id,opportunity_key,event_type,event_id)')

