from __future__ import annotations
from app.database_support import *

class DatabaseMixin3:
        async def _ensure_vehicle_foundation_schema(self, db: aiosqlite.Connection) -> None:
            """Install the additive RP vehicle + travel foundation schema."""
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS character_vehicles (\n                    vehicle_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    model_key TEXT NOT NULL,\n                    condition_key TEXT NOT NULL,\n                    city_key TEXT NOT NULL,\n                    purchase_price INTEGER NOT NULL,\n                    estimated_value INTEGER NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'owned',\n                    acquired_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    sold_at TEXT,\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS character_vehicles (\n                    vehicle_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    model_key VARCHAR(64) NOT NULL,\n                    condition_key VARCHAR(24) NOT NULL,\n                    city_key VARCHAR(32) NOT NULL,\n                    purchase_price DECIMAL(65,0) NOT NULL,\n                    estimated_value DECIMAL(65,0) NOT NULL,\n                    status VARCHAR(24) NOT NULL DEFAULT 'owned',\n                    acquired_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    sold_at VARCHAR(64) NULL,\n                    PRIMARY KEY (vehicle_id),\n                    KEY idx_character_vehicles_owner (guild_id, user_id, status, acquired_at),\n                    KEY idx_character_vehicles_city (guild_id, city_key, status),\n                    CONSTRAINT fk_character_vehicles_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            await aiosqlite.execute_backend_ddl(db, sqlite_sql="\n                CREATE TABLE IF NOT EXISTS vehicle_market_offers (\n                    offer_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    city_key TEXT NOT NULL,\n                    model_key TEXT NOT NULL,\n                    condition_key TEXT NOT NULL,\n                    price INTEGER NOT NULL,\n                    status TEXT NOT NULL DEFAULT 'active',\n                    created_at TEXT NOT NULL,\n                    expires_at TEXT NOT NULL,\n                    buyer_user_id INTEGER,\n                    purchased_at TEXT\n                )\n            ", mysql_sql="\n                CREATE TABLE IF NOT EXISTS vehicle_market_offers (\n                    offer_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    city_key VARCHAR(32) NOT NULL,\n                    model_key VARCHAR(64) NOT NULL,\n                    condition_key VARCHAR(24) NOT NULL,\n                    price DECIMAL(65,0) NOT NULL,\n                    status VARCHAR(24) NOT NULL DEFAULT 'active',\n                    created_at VARCHAR(64) NOT NULL,\n                    expires_at VARCHAR(64) NOT NULL,\n                    buyer_user_id BIGINT UNSIGNED NULL,\n                    purchased_at VARCHAR(64) NULL,\n                    PRIMARY KEY (offer_id),\n                    KEY idx_vehicle_market_city (guild_id, city_key, status, expires_at),\n                    KEY idx_vehicle_market_buyer (guild_id, buyer_user_id, purchased_at)\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ")
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS character_travel_history (\n                    travel_id INTEGER PRIMARY KEY AUTOINCREMENT,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    from_city_key TEXT NOT NULL,\n                    to_city_key TEXT NOT NULL,\n                    mode_key TEXT NOT NULL,\n                    cost INTEGER NOT NULL,\n                    vehicle_id INTEGER,\n                    created_at TEXT NOT NULL,\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS character_travel_history (\n                    travel_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    from_city_key VARCHAR(32) NOT NULL,\n                    to_city_key VARCHAR(32) NOT NULL,\n                    mode_key VARCHAR(24) NOT NULL,\n                    cost DECIMAL(65,0) NOT NULL,\n                    vehicle_id BIGINT UNSIGNED NULL,\n                    created_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (travel_id),\n                    KEY idx_character_travel_user (guild_id, user_id, created_at),\n                    CONSTRAINT fk_character_travel_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS vehicle_state (\n                    vehicle_id INTEGER PRIMARY KEY,\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    is_primary INTEGER NOT NULL DEFAULT 0,\n                    issue_key TEXT,\n                    issue_revealed INTEGER NOT NULL DEFAULT 0,\n                    last_service_at TEXT,\n                    updated_at TEXT NOT NULL,\n                    FOREIGN KEY (vehicle_id) REFERENCES character_vehicles(vehicle_id) ON DELETE CASCADE\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS vehicle_state (\n                    vehicle_id BIGINT UNSIGNED NOT NULL,\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    is_primary TINYINT(1) NOT NULL DEFAULT 0,\n                    issue_key VARCHAR(24) NULL,\n                    issue_revealed TINYINT(1) NOT NULL DEFAULT 0,\n                    last_service_at VARCHAR(64) NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (vehicle_id),\n                    KEY idx_vehicle_state_owner (guild_id, user_id, is_primary),\n                    CONSTRAINT fk_vehicle_state_vehicle\n                        FOREIGN KEY (vehicle_id)\n                        REFERENCES character_vehicles (vehicle_id)\n                        ON UPDATE CASCADE ON DELETE CASCADE\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_vehicle_state_owner ON vehicle_state(guild_id,user_id,is_primary)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_vehicles_owner ON character_vehicles(guild_id,user_id,status,acquired_at)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_vehicles_city ON character_vehicles(guild_id,city_key,status)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_vehicle_market_city ON vehicle_market_offers(guild_id,city_key,status,expires_at)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_vehicle_market_buyer ON vehicle_market_offers(guild_id,buyer_user_id,purchased_at)')
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_travel_user ON character_travel_history(guild_id,user_id,created_at)')

        async def _ensure_police_foundation_schema(self, db: aiosqlite.Connection) -> None:
            """Install the additive RP police-attention foundation schema."""
            await aiosqlite.execute_backend_ddl(db, sqlite_sql='\n                CREATE TABLE IF NOT EXISTS character_police_state (\n                    guild_id INTEGER NOT NULL,\n                    user_id INTEGER NOT NULL,\n                    attention_points INTEGER NOT NULL DEFAULT 0,\n                    last_decay_at TEXT NOT NULL,\n                    updated_at TEXT NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    FOREIGN KEY (guild_id, user_id) REFERENCES characters(guild_id, user_id) ON DELETE RESTRICT\n                )\n            ', mysql_sql='\n                CREATE TABLE IF NOT EXISTS character_police_state (\n                    guild_id BIGINT UNSIGNED NOT NULL,\n                    user_id BIGINT UNSIGNED NOT NULL,\n                    attention_points SMALLINT UNSIGNED NOT NULL DEFAULT 0,\n                    last_decay_at VARCHAR(64) NOT NULL,\n                    updated_at VARCHAR(64) NOT NULL,\n                    PRIMARY KEY (guild_id, user_id),\n                    KEY idx_character_police_attention (guild_id, attention_points, updated_at),\n                    CONSTRAINT fk_character_police_character\n                        FOREIGN KEY (guild_id, user_id)\n                        REFERENCES characters (guild_id, user_id)\n                        ON UPDATE CASCADE ON DELETE RESTRICT\n                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci\n            ')
            if not aiosqlite.using_mysql():
                await db.execute('CREATE INDEX IF NOT EXISTS idx_character_police_attention ON character_police_state(guild_id,attention_points,updated_at)')

