from __future__ import annotations

# Yoru v3.8 - Community Management defaults.
# Guild-specific overrides live in guild_state and are edited through /settings.

SUGGESTIONS_DEFAULT_ENABLED = False
SUGGESTIONS_ALLOW_ANONYMOUS = False
SUGGESTIONS_MAX_LENGTH = 1800

POLLS_DEFAULT_ENABLED = True
POLLS_STAFF_ONLY_DEFAULT = False
POLLS_DEFAULT_DURATION_MINUTES = 60
POLLS_MIN_DURATION_MINUTES = 1
POLLS_MAX_DURATION_MINUTES = 7 * 24 * 60
POLLS_MAX_OPTIONS = 5

GIVEAWAYS_DEFAULT_ENABLED = True
GIVEAWAYS_DEFAULT_DURATION_MINUTES = 60
GIVEAWAYS_MIN_DURATION_MINUTES = 1
GIVEAWAYS_MAX_DURATION_MINUTES = 30 * 24 * 60
GIVEAWAYS_MAX_WINNERS = 10

STARBOARD_DEFAULT_ENABLED = False
STARBOARD_DEFAULT_THRESHOLD = 3
STARBOARD_MIN_THRESHOLD = 1
STARBOARD_MAX_THRESHOLD = 25
STARBOARD_EMOJI = "⭐"

AFK_DEFAULT_ENABLED = True
AFK_MAX_REASON_LENGTH = 300
AFK_MENTION_NOTICE_COOLDOWN_SECONDS = 12

STICKY_DEFAULT_ENABLED = True
STICKY_DEFAULT_EVERY_MESSAGES = 8
STICKY_MIN_EVERY_MESSAGES = 2
STICKY_MAX_EVERY_MESSAGES = 100
STICKY_MAX_LENGTH = 1800
STICKY_REPOST_COOLDOWN_SECONDS = 12

# Safety caps for restore at startup so one malformed/stale guild cannot create
# an unbounded amount of persistent views/tasks.
MAX_RESTORED_SUGGESTIONS = 500
MAX_RESTORED_POLLS = 250
MAX_RESTORED_GIVEAWAYS = 250
