from __future__ import annotations

# Yoru v3.13 Social Economy defaults.

# Player marketplace
PLAYER_MARKET_TAX_RATE = 0.05
PLAYER_MARKET_LISTING_HOURS = 72
PLAYER_MARKET_MAX_ACTIVE_PER_USER = 20
PLAYER_MARKET_MAX_QUANTITY = 999
PLAYER_MARKET_MIN_UNIT_PRICE = 1_000
PLAYER_MARKET_PAGE_SIZE = 10

# Custom server shop
SERVER_SHOP_MAX_ITEMS = 50
SERVER_SHOP_DEFAULT_EMOJI = "🎁"
SERVER_SHOP_MAX_NAME = 80
SERVER_SHOP_MAX_DESCRIPTION = 300
SERVER_SHOP_MAX_STOCK = 1_000_000
SERVER_SHOP_MAX_PER_USER = 10_000
SERVER_SHOP_MAX_TEMP_ROLE_MINUTES = 60 * 24 * 365
SERVER_SHOP_REWARD_TYPES = ("role", "temporary_role", "custom_role", "temporary_custom_role", "item", "custom")

# PvP gambling
PVP_MIN_STAKE = 1_000
PVP_CHALLENGE_SECONDS = 120
PVP_RPS_SECONDS = 120
PVP_GAMES = ("coinflip", "dice", "rps")

# Background maintenance
SOCIAL_CLEANUP_SECONDS = 60

# PvP Casino visual standard
PVP_RENDER_CONCURRENCY = 2
PVP_VISUAL_ANIMATION_SECONDS = 3.35
PVP_RPS_VISUAL_ANIMATION_SECONDS = 2.45
