from __future__ import annotations
from .jobs_projection_support_transport_routes import TRANSPORT_SCENARIOS
from .jobs_projection_support_transport_borsod import BORSOD_SCENARIOS, BORSOD_SCENARIO_BY_KEY, BORSOD_PATROL, BORSOD_LOOT_TWISTS
from .jobs_projection_support_transport_twists import TRANSPORT_TWISTS
